version: '2'
services:
#  app:
#    build: .
#    volumes:
#    - .:/app
#    - ~/.m2:/root/.m2
#    working_dir: /app
#    command: bash -c "mvn clean package && java -jar target/quarkus-example-1.0-SNAPSHOT-runner.jar"
#    ports:
#    - 8080:8080
  app:
    build:
      context: .     
      dockerfile: src/main/docker/Dockerfile
    ports:
    - 8080:8080

  prom:
    image: prom/prometheus:v2.8.1
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
    ports:
    - 9090:9090
    depends_on:
    - app

  grafana:
    image: grafana/grafana:6.1.0
    ports:
    - 3000:3000
    depends_on:
    - prom

